# log4j2.properties
status=warn
name=SauceDemoSelenium

# Console appender
appender.console.type=Console
appender.console.name=STDOUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%d{ISO8601} [%t] %-5p %c{1} - %m%n

# File appender
appender.file.type=File
appender.file.name=LOGFILE
appender.file.fileName=target/logs/automation.log
appender.file.layout.type=PatternLayout
appender.file.layout.pattern=%d{ISO8601} [%t] %-5p %c{1} - %m%n

# Loggers
logger.selenium.name=org.openqa.selenium
logger.selenium.level=warn

logger.cucumber.name=io.cucumber
logger.cucumber.level=info

# Root logger
rootLogger.level=info
rootLogger.appenderRefs=stdout,logfile
rootLogger.appenderRef.stdout.ref=STDOUT
rootLogger.appenderRef.logfile.ref=LOGFILE